<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stake Roulette</title>
  
</head>
<body>
<div class="container">
    <div class="header">
        <h1>🎰 Stake Roulette</h1>
        <div class="balance">Баланс: $<span id="balance">1000</span></div>
    </div>

    <div class="roulette-container">
        <div class="roulette-wheel" id="rouletteWheel"></div>
        <div class="roulette-pointer"></div>
    </div>

    <button class="spin-button" id="spinButton">🎲 Крутити</button>

    <div class="betting-section">
        <div class="bet-controls">
            <input type="number" class="bet-input" id="betAmount" value="10" min="1" max="1000">
            <div class="bet-buttons">
                <button class="bet-btn" onclick="setBetAmount(1)">1</button>
                <button class="bet-btn" onclick="setBetAmount(10)">10</button>
                <button class="bet-btn" onclick="setBetAmount(50)">50</button>
                <button class="bet-btn" onclick="setBetAmount(100)">100</button>
            </div>
        </div>

        <div class="total-bet">
            Загальна ставка: $<span id="totalBet">0</span>
        </div>

        <div class="betting-grid">
            <div class="bet-option red" data-bet="red">
                Червоне<br>1:1
            </div>
            <div class="bet-option black" data-bet="black">
                Чорне<br>1:1
            </div>
            <div class="bet-option green" data-bet="even">
                Парне<br>1:1
            </div>
            <div class="bet-option green" data-bet="odd">
                Непарне<br>1:1
            </div>
            <div class="bet-option red" data-bet="1-18">
                1-18<br>1:1
            </div>
            <div class="bet-option black" data-bet="19-36">
                19-36<br>1:1
            </div>
        </div>

        <div class="numbers-grid" id="numbersGrid">
            <!-- Numbers will be generated by JavaScript -->
        </div>

        <button class="clear-bets" onclick="clearAllBets()">Очистити ставки</button>
    </div>
</div>

<div class="modal" id="resultModal">
    <div class="modal-content">
        <h2 id="resultTitle">Результат</h2>
        <div class="winning-number" id="winningNumber">0</div>
        <div id="resultMessage"></div>
        <div id="winAmount"></div>
    </div>
</div>

<script>
    // Налаштування гри
    let balance = 1000;
    let isSpinning = false;
    let bets = {};
    let totalBetAmount = 0;

    // Числа рулетки з кольорами
    const rouletteNumbers = [
        {number: 0, color: 'green'},
        {number: 32, color: 'red'}, {number: 15, color: 'black'}, {number: 19, color: 'red'},
        {number: 4, color: 'black'}, {number: 21, color: 'red'}, {number: 2, color: 'black'},
        {number: 25, color: 'red'}, {number: 17, color: 'black'}, {number: 34, color: 'red'},
        {number: 6, color: 'black'}, {number: 27, color: 'red'}, {number: 13, color: 'black'},
        {number: 36, color: 'red'}, {number: 11, color: 'black'}, {number: 30, color: 'red'},
        {number: 8, color: 'black'}, {number: 23, color: 'red'}, {number: 10, color: 'black'},
        {number: 5, color: 'red'}, {number: 24, color: 'black'}, {number: 16, color: 'red'},
        {number: 33, color: 'black'}, {number: 1, color: 'red'}, {number: 20, color: 'black'},
        {number: 14, color: 'red'}, {number: 31, color: 'black'}, {number: 9, color: 'red'},
        {number: 22, color: 'black'}, {number: 18, color: 'red'}, {number: 29, color: 'black'},
        {number: 7, color: 'red'}, {number: 28, color: 'black'}, {number: 12, color: 'red'},
        {number: 35, color: 'black'}, {number: 3, color: 'red'}, {number: 26, color: 'black'}
    ];

    // Ініціалізація гри
    function initGame() {
        generateNumbersGrid();
        updateBalance();
        updateTotalBet();
    }

    // Генерація сітки номерів
    function generateNumbersGrid() {
        const numbersGrid = document.getElementById('numbersGrid');
        numbersGrid.innerHTML = '';

        for (let i = 0; i <= 36; i++) {
            const numberDiv = document.createElement('div');
            numberDiv.className = 'number-bet';
            numberDiv.textContent = i;
            numberDiv.dataset.bet = i;
            numberDiv.onclick = () => placeBet(i);

            if (i === 0) {
                numberDiv.classList.add('green');
            } else if ([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36].includes(i)) {
                numberDiv.classList.add('red');
            } else {
                numberDiv.classList.add('black');
            }

            numbersGrid.appendChild(numberDiv);
        }
    }

    // Встановлення суми ставки
    function setBetAmount(amount) {
        document.getElementById('betAmount').value = amount;
    }

    // Розміщення ставки
    function placeBet(betType) {
        if (isSpinning) return;

        const betAmount = parseInt(document.getElementById('betAmount').value);
        if (betAmount <= 0 || betAmount > balance) return;

        if (!bets[betType]) {
            bets[betType] = 0;
        }

        bets[betType] += betAmount;
        totalBetAmount += betAmount;

        updateBetDisplay();
        updateTotalBet();
    }

    // Додавання обробників подій для ставок
    document.querySelectorAll('.bet-option').forEach(option => {
        option.addEventListener('click', () => {
            placeBet(option.dataset.bet);
        });
    });

    // Оновлення відображення ставок
    function updateBetDisplay() {
        // Очищення попередніх виділень
        document.querySelectorAll('.bet-option.active, .number-bet.active').forEach(el => {
            el.classList.remove('active');
            const amountEl = el.querySelector('.bet-amount');
            if (amountEl) amountEl.remove();
        });

        // Відображення активних ставок
        Object.keys(bets).forEach(betType => {
            const amount = bets[betType];
            if (amount > 0) {
                const element = document.querySelector(`[data-bet="${betType}"]`);
                if (element) {
                    element.classList.add('active');

                    const amountEl = document.createElement('div');
                    amountEl.className = 'bet-amount';
                    amountEl.textContent = amount;
                    element.appendChild(amountEl);
                }
            }
        });
    }

    // Очищення всіх ставок
    function clearAllBets() {
        if (isSpinning) return;

        bets = {};
        totalBetAmount = 0;
        updateBetDisplay();
        updateTotalBet();
    }

    // Оновлення загальної ставки
    function updateTotalBet() {
        document.getElementById('totalBet').textContent = totalBetAmount;
    }

    // Оновлення балансу
    function updateBalance() {
        document.getElementById('balance').textContent = balance;
    }

    // Обертання рулетки
    function spinRoulette() {
        if (isSpinning || totalBetAmount === 0 || totalBetAmount > balance) return;

        isSpinning = true;
        balance -= totalBetAmount;
        updateBalance();

        document.getElementById('spinButton').disabled = true;
        document.getElementById('spinButton').textContent = '🔄 Крутиться...';

        // Випадкове число
        const randomIndex = Math.floor(Math.random() * rouletteNumbers.length);
        const winningNumber = rouletteNumbers[randomIndex];

        // Обертання колеса
        const wheel = document.getElementById('rouletteWheel');
        const rotation = 360 * 5 + (randomIndex * (360 / rouletteNumbers.length));
        wheel.style.transform = `rotate(${rotation}deg)`;

        // Показ результату через 3 секунди
        setTimeout(() => {
            showResult(winningNumber);
            isSpinning = false;
            document.getElementById('spinButton').disabled = false;
            document.getElementById('spinButton').textContent = '🎲 Крутити';
        }, 3000);
    }

    // Показ результату
    function showResult(winningNumber) {
        const modal = document.getElementById('resultModal');
        const resultTitle = document.getElementById('resultTitle');
        const winningNumberEl = document.getElementById('winningNumber');
        const resultMessage = document.getElementById('resultMessage');
        const winAmountEl = document.getElementById('winAmount');

        winningNumberEl.textContent = winningNumber.number;
        winningNumberEl.className = `winning-number ${winningNumber.color}`;

        let totalWin = 0;
        let winningBets = [];

        // Перевірка виграшних ставок
        Object.keys(bets).forEach(betType => {
            const betAmount = bets[betType];
            if (betAmount > 0) {
                let isWin = false;
                let multiplier = 0;

                // Перевірка різних типів ставок
                if (betType == winningNumber.number) {
                    isWin = true;
                    multiplier = 35; // 35:1 для прямої ставки
                } else if (betType === 'red' && winningNumber.color === 'red') {
                    isWin = true;
                    multiplier = 1;
                } else if (betType === 'black' && winningNumber.color === 'black') {
                    isWin = true;
                    multiplier = 1;
                } else if (betType === 'even' && winningNumber.number % 2 === 0 && winningNumber.number !== 0) {
                    isWin = true;
                    multiplier = 1;
                } else if (betType === 'odd' && winningNumber.number % 2 === 1) {
                    isWin = true;
                    multiplier = 1;
                } else if (betType === '1-18' && winningNumber.number >= 1 && winningNumber.number <= 18) {
                    isWin = true;
                    multiplier = 1;
                } else if (betType === '19-36' && winningNumber.number >= 19 && winningNumber.number <= 36) {
                    isWin = true;
                    multiplier = 1;
                }

                if (isWin) {
                    const winAmount = betAmount * (multiplier + 1);
                    totalWin += winAmount;
                    winningBets.push({type: betType, amount: winAmount});
                }
            }
        });

        balance += totalWin;
        updateBalance();

        // Відображення результату
        if (totalWin > 0) {
            resultTitle.textContent = '🎉 Виграш!';
            resultTitle.className = 'win';
            resultMessage.textContent = `Номер ${winningNumber.number} (${winningNumber.color === 'red' ? 'червоне' : winningNumber.color === 'black' ? 'чорне' : 'зелене'})`;
            winAmountEl.textContent = `Виграш: $${totalWin}`;
            winAmountEl.className = 'win';
        } else {
            resultTitle.textContent = '😞 Програш';
            resultTitle.className = 'lose';
            resultMessage.textContent = `Номер ${winningNumber.number} (${winningNumber.color === 'red' ? 'червоне' : winningNumber.color === 'black' ? 'чорне' : 'зелене'})`;
            winAmountEl.textContent = `Програш: $${totalBetAmount}`;
            winAmountEl.className = 'lose';
        }

        // Показ модального вікна
        modal.classList.add('show');

        // Приховування через 2 секунди
        setTimeout(() => {
            modal.classList.remove('show');
            clearAllBets();
        }, 2000);
    }

    // Обробник кнопки обертання
    document.getElementById('spinButton').addEventListener('click', spinRoulette);

    // Ініціалізація гри при завантаженні
    window.addEventListener('load', initGame);
</script>
</body>
</html>